// temporary list of 4 names
export default [
  {
    id: 0,
    name: 'Astghik',
    sex: 'female',
    meaning: '"little star". Derived from the Armenian word "astgh" meaning "star" and the suffix "ig" meaning "little." Famous real-life people named Astghik Astghik in song, story & screen. Astghik is the Armenian goddess of fertility and love.',
  }, {
      id: 1,
      name: 'Lusine',
      sex: 'female',
      meaning: 'Lusine is a feminine given name derives from the Armenian “Lusin (Լուսին)”, meaning “moon”. The ancient Armenians, like the Latins, possessed two different names for the moon.'
  }, {
      id: 2,
      name: 'Hayk', 
      sex: 'male',
      meaning: 'Hayk the Great (Armenian: Հայկ, Armenian pronunciation: [hajk]), or The Great Hayk, also known as Hayk Nahapet (Հայկ Նահապետ, Armenian pronunciation: [hajk nahapɛt], Hayk the "head of family" or patriarch), is the legendary patriarch and founder of the Armenian nation.'
  }, {
      id: 3,
      name: 'Razmik',
      sex: 'male',
      meaning: 'little soldier/fighter'
  }
];

// old, longer list that needs formatting
// const randomNames = [
//   "Abaven",
//   "Alexan",
//   "Aharon",
//   "Antranig",
//   "Antrias",
//   "Anoushavan",
//   "Andon",
//   "Arnag",
//   "Arno",
//   "Adis",
//   "Apkar",
//   "Apraham",
//   "Ara",
//   "Aram",
//   "Aramazt",
//   "Aramais",
//   "Aran",
//   "Arakel",
//   "Ararad",
//   "Araz",
//   "Arbi",
//   "Arpag",
//   "Arpoun",
//   "Arkam",
//   "Aren",
//   "Arek",
//   "Arzouman",
//   "Ared",
//   "Artoun",
//   "Arisdages",
//   "Arman",
//   "Armenag",
//   "Armen",
//   "Arshalouys",
//   "Arshak",
//   "Arsham",
//   "Arshavir",
//   "Arshen",
//   "Arsen",
//   "Ardashes",
//   "Ardavast",
//   "Ardavan",
//   "Ardem",
//   "Artur",
//   "Artyom",
//   "Ashod",
//   "Asadour",
//   "Asdvadzadour",
//   "Avak",
//   "Avedis",
//   "Avedig",
//   "Azad",
//   "Azniv",
//   "Baghdasar",
//   "Barouyr",
//   "Barsam",
//   "Bedros",
//   "Berj",
//   "Poghos",
//   "Datev",
//   "Dajad",
//   "Dertad",
//   "Diana(Divine)",
//   "Dikran",
//   "Dzeroun",
//   "Dzovag",
//   "Dzaghig",
//   "Dzovinar",
//   "Donig",
//   "Ellis",
//   "Eshkhan",
//   "Esahag",
//   "Emin",
//   "Emmanouel",
//   "Et'an",
//   "Gakig",
//   "Gamsar",
//   "Gamo",
//   "Gaydzag",
//   "Karabed",
//   "Karen",
//   "Garbis",
//   "Garo",
//   "Giragos",
//   "Guregh",
//   "Gomidas",
//   "Gosdan",
//   "Gosdantin",
//   "Goryoun",
//   "Gdridg",
//   "Gunar",
//   "Ghazar",
//   "Ghazaros",
//   "Gharib",
//   "Ghevont",
//   "Ghougas",
//   "Ghoungyanos",
//   "Genos",
//   "Hamazasb",
//   "Hamlet",
//   "Hamparzoum",
//   "Hayastan",
//   "Haig",
//   "Haygazoun",
//   "Haygaz",
//   "Haygag",
//   "Haygaram",
//   "Hayrabed",
//   "Hayrig",
//   "Hetoum",
//   "Hmayag",
//   "Hraztan",
//   "Hrag",
//   "Hrahad",
//   "Hrayr",
//   "Hrant",
//   "Hratch",
//   "Hravart",
//   "Hapet",
//   "Hagop",
//   "Harutyun",
//   "Haro",
//   "Hovagem",
//   "Hovasap",
//   "Hovhannes",
//   "Hovnan",
//   "Hovnatan",
//   "Hovsep",
//   "Jannig",
//   "Jirayr",
//   "Jivan",
//   "Kapriel",
//   "Kachig",
//   "Kakig",
//   "Kazavon",
//   "Kaloust",
//   "Kamer",
//   "Kami",
//   "Karnig",
//   "Kasbar",
//   "Karekin",
//   "Karen",
//   "Kegham",
//   "Keghart",
//   "Keghon",
//   "Kersam",
//   "Kevork",
//   "Kissag",
//   "Kud",
//   "Kousan",
//   "Kourken",
//   "Krikor",
//   "Krisdapor",
//   "Khajag",
//   "Khatchadour",
//   "Khatcheres",
//   "Khatchig",
//   "Khigar",
//   "Khosrov",
//   "Khoren",
//   "Lernig",
//   "Levon",
//   "Libarid",
//   "Loris",
//   "Luca",
//   "Matous",
//   "Majag",
//   "Malkhas",
//   "Magar",
//   "Mampre",
//   "Mamigon",
//   "Manajihr",
//   "Manase",
//   "Mangasar",
//   "Manuel",
//   "Manough",
//   "Mashdots",
//   "Massis",
//   "Madat",
//   "Madteos",
//   "Markar",
//   "Margos",
//   "Mardig",
//   "Mardiros",
//   "Mardoun",
//   "Matsag",
//   "Melek",
//   "Melkon",
//   "Mekhag",
//   "Meghrig",
//   "Mesrob",
//   "Meroujan",
//   "Mjej",
//   "Miadzin",
//   "Mihran",
//   "Mihrtad",
//   "Minas",
//   "Misak",
//   "Mouron",
//   "Mikaiel",
//   "Mleh",
//   "Mkhitar",
//   "Mgrditch",
//   "Mgrdoum",
//   "Mher",
//   "Mnatsagan",
//   "Movses",
//   "Moushegh",
//   "Moushe",
//   "Mourad",
//   "Natan",
//   "Nazar",
//   "Nazaret",
//   "Nahabed",
//   "Nar",
//   "Narek",
//   "Navasart",
//   "Nbad",
//   "Nerseh",
//   "Nerses",
//   "Nigol",
//   "Nigoghos",
//   "Njteh",
//   "Norayr",
//   "Norhad",
//   "Norvan",
//   "Noubar",
//   "Nourhan",
//   "Noy",
//   "Nshan",
//   "Oksen",
//   "Ohan",
//   "Onnig",
//   "Oshin",
//   "Oshakan",
//   "Oda",
//   "Ovsanna",
//   "Papken",
//   "Pakrad",
//   "Pagour",
//   "Partogh",
//   "Partoghimeos",
//   "Parkhoutar",
//   "Parounag",
//   "Parsegh",
//   "Peklar",
//   "Penyamin",
//   "Pertag",
//   "Puzant",
//   "Purad",
//   "Paylag",
//   "Panig",
//   "Panos",
//   "Paren",
//   "Parnag",
//   "Paramaz",
//   "Pillibos",
//   "Potorik",
//   "Razmig",
//   "Raphael",
//   "Reteos",
//   "Robert",
//   "Rosdom",
//   "Rupen",
//   "Raffi",
//   "Sahag",
//   "Sami",
//   "Samuel",
//   "Samson",
//   "Sanasar",
//   "Sanatroug",
//   "Sandis",
//   "Sasoun",
//   "Sarkis",
//   "Sarhad",
//   "Saro",
//   "Sarven",
//   "Setrag",
//   "Sebouh",
//   "Serj",
//   "Serop",
//   "Serovpe",
//   "Sero",
//   "Sevag",
//   "Sevan",
//   "Set",
//   "Semag",
//   "Simon",
//   "Sinan",
//   "Sion",
//   "Sis",
//   "Sisag",
//   "Sirak",
//   "Sirekan",
//   "Sipan",
//   "Smpad",
//   "Sograd",
//   "Soghomon",
//   "Souren",
//   "Sourmag",
//   "Soukias",
//   "Stephan",
//   "Sos",
//   "Srabion",
//   "Sona",
//   "Talis",
//   "Taniel",
//   "Tavtag",
//   "Tavit",
//   "Terenig",
//   "Trasdamard",
//   "Tro",
//   "Takvor",
//   "Tateos",
//   "Tatoul",
//   "Tevan",
//   "Teotig",
//   "Tovmas",
//   "Torkom",
//   "Toros",
//   "Tsolag",
//   "Tsakig",
//   "Vazken",
//   "Vazrig",
//   "Vakhtang",
//   "Vahagn",
//   "Vahaken",
//   "Vahan",
//   "Vahe",
//   "Vahram",
//   "Vahrej",
//   "Vagharsh",
//   "Vagharshag",
//   "Vaghinag",
//   "Van",
//   "Vanagan",
//   "Vanant",
//   "Vanadour",
//   "Vanig",
//   "Vanoush",
//   "Vatche",
//   "Vasag",
//   "Vasbourag",
//   "Varak",
//   "Varaztad",
//   "Varant",
//   "Vart",
//   "Vartan",
//   "Vartavar",
//   "Vartivar",
//   "Vartkes",
//   "Varteres",
//   "Varos",
//   "Varoujan",
//   "Vicken",
//   "Vigen",
//   "Vram",
//   "Vrej",
//   "Vrtanes",
//   "Vosgan",
//   "Vosdanig",
//   "Yeghya",
//   "Yeghisheh",
//   "Yeghiazar",
//   "Yeprem",
//   "Yesayi",
//   "Yeranos",
//   "Yerimya",
//   "Yervant",
//   "Yetvart",
//   "Yeznig",
//   "Yezras",
//   "Zadig",
//   "Zareh",
//   "Zarzant",
//   "Zarmayr",
//   "Zarmig",
//   "Zaven",
//   "Zakariya",
//   "Zohrag",
//   "Zohrab",
//   "Zoravar",
//   "AGHAVNI ( dove)",
//   "ALTOON ( gold)",
//   "ANAHID ( pure",
//   "ANKINE ( valuable)",
//   "ANOUSH ( sweet)",
//   "AREV ( sun)",
//   "ARMAVENE ( palm-tree)",
//   "ARMENOUHEE ( from Armenia)",
//   "ARMENOUHI ( from Armenia)",
//   "AROUSEAK ( morning star)",
//   "ARPI ( sun)",
//   "ARUSIAG ( morning star)",
//   "ARUSIAK ( morning star)",
//   "ASDGHIG ( Venus)",
//   "ASTGHIK ( Venus)",
//   "AZNIV ( noble)",
//   "BADASHAN ( answer)",
//   "BAGMASTI ( consort of the deity Haldi)",
//   "BERJOUHI ( from Berjou (?))",
//   "DZAGHIG ( flower)",
//   "DZIADZAN ( rainbow)",
//   "GADAR ( summit)",
//   "GAYANE ( the name of a saint; (melody?))",
//   "HAIGOUHI ( father's female)",
//   "HALTOON ( gold (?))",
//   "HASMIG ( jasmine)",
//   "HATOON ( lady)",
//   "HEGHNAR ( father's daughter (?))",
//   "HEYGOUHEE ( father's female)",
//   "HUNAZANT ( obedient)",
//   "KEGHANOUSH ( from the fortress of Kegha (?))",
//   "KNARIG ( (?))",
//   "KOHAR ( jewel)",
//   "LOOSIG ( little light)",
//   "LOOSINTAK ( crown of light)",
//   "LOUSAPER ( light-bringer)",
//   "LOUSNTAK ( crown of light)",
//   "LUCINE ( light)",
//   "LYUDMILA ( people's love)",
//   "MAKROUHI ( from the Makrou?)",
//   "MANISHAK ( violet flower)",
//   "MANNIG ( (?))",
//   "MARGARID ( pearl)",
//   "MEGHRANOUSH ( honey-sweet)",
//   "NAIRI ( Armenian)",
//   "NAZANI ( delicate)",
//   "NOUSHIG ( little almond)",
//   "NOUVART ( little rose)",
//   "OVSANNA ( deliver us",
//   "PERGROUHI ( joy)",
//   "POURASDAN ( garden of flowers)",
//   "PRAPION ( laurel",
//   "SERPOUHI ( holiness)",
//   "SERPUHI ( holiness)",
//   "SEVAN ( Black Van)",
//   "SHNORHIG ( (?))",
//   "SHOGHAGAT ( rays from above)",
//   "SHOUSHAN ( lily)",
//   "SHUSHAN ( lily)",
//   "SIRAN ( beautiful)",
//   "SIROUN ( lovely)",
//   "SIRPUHI ( holiness)",
//   "SIRVART ( beautiful rose)",
//   "SIRVAT ( beautiful rose)",
//   "SOSI ( plane-tree)",
//   "SRPOUHI ( holiness)",
//   "SURPOOHE ( holiness)",
//   "TAKOOHE ( queen)",
//   "TAKOUHI ( queen)",
//   "TANGAKIN ( precious)",
//   "TEGHTSANIG ( canary bird)",
//   "TEGHTSUN ( yellow-haired)",
//   "TETER ( butterfly)",
//   "VARTANOUSH ( rose-sweet)",
//   "VARTENI ( rose-tree)",
//   "VARTER ( rose)",
//   "VARTIG ( little rose)",
//   "VARTITER ( rose-leaf or rose-petal)",
//   "VARTOUHI ( rose woman)",
//   "VOSGETEL ( gold-thread)",
//   "VOSGI ( gold)",
//   "VOSHKIE ( gold)",
//   "YEGHNIG ( fawn)",
//   "YERCHANIG ( fortunate",
//   "YEVA ( Eve; life)",
//   "ZABEL ( God is my oath or oath of Baal)",
//   "ZANAZAN ( distinct",
//   "ZIAZAN ( rainbow)",
//   "ZMRUKHT ( emerald)",
//   "ZVART ( black (?); sword (?))",
// ];
